### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by EmreOzkose** [mindslab-ai/nuwave#3]
Hi! Thank you for sharing your code.

Do you plan to share pretrained models?

**Comment by junjun3518** [comment]
Hi!
I need to talk about this with my company, so I am not sure it is possible.

**Comment by EmreOzkose** [comment]
I see, thank you.

**Comment by michael-jan** [comment]
Any updates? A pretrained model would be super duper helpful! :)

**Comment by freds0** [comment]
Yes, checkpoints available at https://github.com/mindslab-ai/nuwave/issues/18.
